### ISSUE TITLE
Samsung S6 Edge stops receving/sending cgm data

### ISSUE THREAD

**Issue by ltomovski** [pazaan/640gAndroidUploader#65] opened 2016-07-12 01:32 UTC
once started (we use NS only in the night) it works OK .. but then some time later it act as it is not working

#### Your Environment

* Uploader Version Number: 0.4.0
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung S6 Edge
* Android Version Number (e.g. use 4.4 for 4.4.4): 6.0.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile):Airplane mode, WiFi ON
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): Nightscout
version 0.9.0-beta3

#### Brief Explanation of Issue

it just stops sending data .. if I unlock the phone it starts working again 
On the battery menu I have set NS app to turn off - not saving power on this app
![interrupted](https://cloud.githubusercontent.com/assets/19262121/16752349/36f78006-47e9-11e6-9b5e-3d84c7edf4b6.gif)
Also on the main screen there are lots of repeating logs

Connecting to the Contour Next Link...
Connecting to Contour Next Link on channel 20.
Connecting to the Contour Next Link...
Connecting to Contour Next Link on channel 20.
Connecting to the Contour Next Link...
Connecting to Contour Next Link on channel 20.

#### Severity Score

4

**Comment by pazaan** [comment] 2016-07-12 02:37
Duplicate of #32

**Closed by pazaan** 2016-07-12 02:37 UTC
Labels: duplicate
