### ISSUE TITLE
CareLink login fail

### ISSUE THREAD

**Issue by Sir-ka** [pazaan/640gAndroidUploader#13] opened 2016-05-16 14:12 UTC
I can´t register a USB stick. It's my fault or application error .

The first field is the username and password of the second, right?

(Screenshot) https://drive.google.com/file/d/0B0djxvd9fF3gVDlSR3lzYVpybDg/view?usp=sharing

OK: username, password, OTG (SE Z1 Compact, os 5.1.1)

**Comment by HenrikHL** [comment] 2016-05-16 18:16
Top field is the UserName and bottom field is the password.
I cannot register my USB stick either...

**Comment by wright-david** [comment] 2016-05-16 21:09
There is a fix in v0.1.1 relating to passwords
https://github.com/pazaan/Medtronic640gUploader/releases

Please could you re-test if you weren't using that version?

Also can you check your Carelink login via browser on your device, to double check the web service is available?

**Comment by Sir-ka** [comment] 2016-05-17 07:57
No it is´n. I tested in v0.1.1. (login via v0.1 failed too) 
Server to login are carelink.minimed.com or carelink.minimed.eu? I try login via both server (registred as USA person and Czech person)

Carelink login via browser on device was successful

**Comment by HenrikHL** [comment] 2016-05-17 08:00
I also still have the login problem - even though I opened the case that
was fixed in v0.1.1 (regarding non-latin characters in UserName)

I only have carelink.minimed.eu account (as I am European citizen)

2016-05-17 9:57 GMT+02:00 Sir-ka <notifications@github.com>:

**Comment by pazaan** [comment] 2016-05-17 10:48
The CareLink site was down yesterday. Can you confirm that you can log into CareLink, and try again with the app?

**Comment by Sir-ka** [comment] 2016-05-17 11:14
Log in to Carelink is succesful, connectin via app failed. "Username or pass. are incorect"

**Comment by pazaan** [comment] 2016-05-17 11:26
The only real way I can help to resolve these is for you to DM me on Gitter so that we can debug together.

**Comment by kellylove1** [comment] 2016-05-17 13:34
Please, can someone help me?

**Comment by HenrikHL** [comment] 2016-05-17 18:11
I have just DM'ed you on Gitter - let me know what I can help you with...

**Comment by kellylove1** [comment] 2016-05-17 21:37
I can't log in with the app at carelink.minimed.eu
How can I resolve it?

**Comment by HenrikHL** [comment] 2016-05-18 07:45
I think I have found the reason why it doesn't work for me. I don't use the "Bayer Contour NextLink" to connect to the internet. I use a "Carelink USB" stick. It occurred to me when you asked me to change password on the carelink server. As my NextLink is never connected to any computer - this would not help ;-)

I (my daughter) only uses the NextLink to measure her BS (which then transfers the BS level to the pump wirelessly) - we use the CareLink to transfer the data from the pump to the carelink servers.

I have taken a photo of the CareLink I use - is there ever going to be support for this?
![2016-05-18 09 43 01](https://cloud.githubusercontent.com/assets/3489388/15351012/28394f9a-1cdd-11e6-97d5-69e09db11edb.jpg)

I am writing here because others might have the same setup as me...

**Comment by kellylove1** [comment] 2016-05-18 14:04
thank you very much for your help.
I solved the problem by removing the number from my username and password
Now it seems to work correctly

**Comment by HenrikHL** [comment] 2016-05-18 14:39
Hmm - I have numbers in my password - is that what you are referring to? Or what number are you talking about?

**Comment by kellylove1** [comment] 2016-05-18 15:53
yes, I delete all the numbers in username and password an now it work!

**Comment by pazaan** [comment] 2016-05-19 10:08
@kellylove1 That doesn't really make any sense to me, but hey, if it's working for you...
@Sir-ka Do any of the above comments help you out?
@HenrikHL I'd have to look at the output of a Wireshark capture from the Carelink USB to see if it's the same protocol.

**Comment by Sir-ka** [comment] 2016-05-19 10:55
reset acc+pass on carelink.minimed.com - doesnt help
reset acc+pass on carelink.minimed.eu - first login was sucessful, but second fail again...

**Comment by pazaan** [comment] 2016-05-19 10:57
The app doesn't use carelink.minimed.com *at all*, so only log in using `carelink.minimed.eu`. At the end of the day, if you can't log in on `carelink.minimed.eu`, you won't be able to log in with the app. I've had login problems with some of my accounts that I've had to call up Medtronic Support for.

**Comment by Sir-ka** [comment] 2016-05-19 11:26
2 day ago I asked for server. Now its working well, so where is the problem?

**Comment by anoukackermans** [comment] 2016-06-05 20:56
Is there already is a solution for the carelink.minimed.eu problem?
I can login on carelink.minimed.eu without problems but when i wan't to register my Contour meter in de APK I get the same error as the original poster. I hope you can help me (and others from europe).

You have don great work building this app!!!

**Comment by Bal00** [comment] 2016-06-05 21:04
@pazaan I wonder if this is linked to an odd problem we had with the Carelink uploader. I had one case where the csv download failed consistently and the only pointer I ever found was in the authentication cookies, where usually one of the variables would have a hard value (looked encoded), instead there was some kind of pointer to careleink.minimed.com. This was a carelink.minimed.eu account in Poland and user reported never having used .com...

**Comment by anoukackermans** [comment] 2016-06-05 21:10
I think the problem is solved. 
I don't know what the sollutions is but I have tried:
- Change my password (no numbers)
- Restarting my phone
- Turn the contour on and off
And now it worked. 

Thanks!

**Comment by kbb01** [comment] 2016-07-27 20:48
Hi I'm getting the issue where I try and register by USB Carelink meter but it says The user name or password is incorrect. I can however login into carelink.minimed.eu without any issues. I've also tried the fix of removing number from my password but this didn't work for me :(

Any suggestions ?

Thanks

**Comment by pazaan** [comment] 2016-07-27 21:44
@kbb01 - have you paired your USB stick with the pump you want to read from? And if so, have you successfully used CareLink to do a pump data upload?

**Comment by kbb01** [comment] 2016-07-28 05:59
HI Thanks for the reply, yes paired the USB stick with the pump (I now have two USB sticks paired with the pump, this new one is the USB stick that is connected to the Moto G (Gen 2) running Android v6.0) I have also successfully used CareLink to do a pump data upload. Only thing I noticed was the S/N in the uploader App shows as 6213-xxxxxxx but in the carelink portal it just show the serial number as BGxxxxxxxB not sure if this has anything to do with it? 

Any thanks for your help

**Comment by pazaan** [comment] 2016-12-04 07:56
Fixed by commit a323eb70b191510f6f954c6c252df16ed0e73acd

**Closed by pazaan** 2016-12-04 07:56 UTC

**Comment by pazaan** [comment] 2017-03-30 07:45
To comment on https://github.com/pazaan/640gAndroidUploader/issues/13#issuecomment-219950859, I don't think that there will ever be support for the CareLink USB 2.4 stick, as it can't be paired with the pump, which requires you to allow the USB stick to read the pump every time it's polled.

**Comment by HenrikHL** [comment] 2017-03-30 09:28
Since version 0.4 there is no need for me to use the CareLink USB 2.4 stick - I am using the Bayer Contour NextLink which works great. In general the app is working great :-)
Thank you @pazaan for this great app - I really appreciate all the hard work you all put in
